- name: Check that the Vagrantfile exists
  stat:
    path: "{{ host_working_directory }}/vagrant/Vagrantfile"
  register: Vagrantfile

- name: "{{ iodo }} VM"
  shell: "{{ cmd }} {{ item.NAME }}"
  args:
    chdir: "{{ host_working_directory }}/vagrant"
  environment:
    NAME:         "{{ item.NAME         | default('VM42') }}"
    CPU:          "{{ item.CPU          | default('1') }}"
    MEMORY:       "{{ item.MEMORY       | default('1024') }}"
    HOSTNAME:     "{{ item.HOSTNAME     | default('VM42') }}"

    IMAGE:        "{{ item.IMAGE        | default('generic/ubuntu2004') }}"
    TAG:          "{{ item.TAG          | default('4.2.16') }}"
    PROVIDER:     "{{ item.PROVIDER     | default('virtualbox') }}"

    NETWORK:      "{{ item.NETWORK      | default('public') }}"
    IP:           "{{ item.IP           | default('192.168.1.42') }}"
    BRIDGE:       "{{ ansible_default_ipv4.interface }}"

    DISABLE_SYNC: "{{ item.DISABLE_SYNC | default('true') }}"
    LOCAL_SYNC:   "{{ item.LOCAL_SYNC   | default('.') }}"
    REMOTE_SYNC:  "{{ item.REMOTE_SYNC  | default('/vagrant') }}"

    PLAYBOOK:     "playbook.yml"
    TASKS_FILE:   "{{ item.TASKS_FILE   | default('') }}"

    SCRIPT_FILE:  "{{ item.SCRIPT_FILE  | default('void') }}"
    SCRIPT_ARGS:  "{{ item.SCRIPT_ARGS  | default('') }}"
  register: response
  with_items: "{{ nodes_vm }}"
  when: cmd and Vagrantfile.stat.exists

- debug:
    msg: 
      - "{{ item.stdout_lines }}"
  with_items:
  - "{{ response.results }}"
  when: 
    - Vagrantfile.stat.exists
    - iodo == "status" or iodo == "validate" or iodo == "destroy" or iodo == "halt"